IoU Benchmark implementation
pmokeev/plane-benchmark pull request #1
Opened 2022-02-07 12:58 UTC by pmokeev

2022-02-07 15:50 UTC, DmiitriyJarosh requested changes

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/utils/metrics.py
> +    return np.union1d(plane_left, plane_right)
Что то я подумал - мб нет смысла выносить юнион и интерсект в утилиты - всего одна строчка получается

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        self, point_cloud: np.ndarray, plane_predicted: np.ndarray, plane_gt: np.ndarray
по имени не понятно что надо в плоскости подавать индексы из облака точек - давайте это отразим в документации или именах переменных

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        point_cloud_predicted: np.ndarray,
аналогично про формат ввода давайте запишем что это лэйблы а не покрашенные облака например

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/utils/metrics.py
> +    for index, value in enumerate(indices_array):
можно красиво через unique,
```
unique = np.unique(labels)  
for label in unique:  
    label_indices = np.where(labels == label)[0]  
```

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/utils/metrics.py
> +def get_dictionary_indices_of_current_label(indices_array: np.ndarray) -> dict:
нэйминг выглядит не очень - это не индексы а лэйблы ведь, да и current лэйбл звучит в названии функции странно - мб лучше group_indices_by_labels?

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        for key, indices in enumerate(point_cloud_predicted):
странно выглядит, зачем нам опять идти по всему массиву лэйблов? Почему нельзя пойти просто по уникальным лэйблам?

2022-02-07 15:50 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        return iou_mean_array.mean()
как это расширяемо с точки зрения способов усреднения? Пока конечно не актуально, но на след задачке придется править) Я бы делал отдельный метод -> cummulate_metric в который передавал бы метрики для каждой пары (мб еще облако и какую то инфу про сами пары, но это зависит от того какие будут варианты cumulative)

2022-02-07 17:01 UTC, DmiitriyJarosh approved these changes

2022-02-07 17:01 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        :param point_cloud: source point cloud
а такое пишут не в базовом классе?

2022-02-07 17:01 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        :param points_predicted_indices: indices of point obtained as a result of segmentation
давайте лучше про что то более приближенное к нам indices of points that belong to one plane obtained as a result of segmentation

2022-02-07 17:01 UTC, DmiitriyJarosh commented on src/metrics/one_value/IoUBenchmark.py
> +        unique = np.unique(point_cloud_predicted_labels)
что с нэймингом? unique_labels, label in unique_labels

2022-02-07 17:54 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +class Benchmark:
давайте сделаем абстрактным - наследование от ABC

2022-02-07 18:12 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +        points_predicted_indices: np.ndarray,
убрать points,  сократить predicted -> pred

2022-02-07 18:12 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +        point_cloud: np.ndarray,
pc_points

2022-02-07 18:12 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +        point_cloud_predicted_labels: np.ndarray,
pred_labels

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +    pc_points: npt.NDArray[np.float64],
а размерность тут никак не отобразить?

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +    metrics: List[
почему здесь список? я думаю что если мы хотим посчитать mean для разных метрик, то можн просто в цикле будет вызвать mean с разными параметрами

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +        pc_points.shape[0] == pred_labels.size
Во всех трех массивах провеяйте еще len(shape) - вдруг нам дадут (n, 3, 5) - тогда ни один ассерт ваш не упадет

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +        pc_points.shape[0] == gt_labels.size
тут лучше смотрится points.size

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +from typing import Callable, List
название файла не benchmark, а что-то типо metrics.py давайте сделаем (потом можно будет распихать реализации mean по разным файлам)

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/metrics/IoUBenchmark.py
> +def iou(
это паблик функция - значит нужны ассерты

2022-02-08 14:30 UTC, DmiitriyJarosh commented on src/utils/metrics.py
> +def group_indices_by_labels(
это private func -- мб ее стоит назвать __group_indices_by_labels() ?

2022-02-08 15:31 UTC, pmokeev commented on src/metrics/Benchmark.py
> +        pc_points.shape[0] == gt_labels.size
why?

2022-02-08 15:36 UTC, pmokeev commented on src/metrics/IoUBenchmark.py
> +def iou(
What asserts can be here? The sizes of arrays can in principle not match and be zero.

2022-02-08 15:49 UTC, pmokeev commented on src/metrics/IoUBenchmark.py
> +def iou(
Added an assertion on the positive size of arrays

2022-02-08 16:42 UTC, DmiitriyJarosh commented on src/metrics/Benchmark.py
> +        pc_points.shape[0] == gt_labels.size
я наверно про лэйблы все таки хотел написать

2022-02-08 16:59 UTC, DmiitriyJarosh approved these changes

2022-02-08 16:59 UTC, DmiitriyJarosh commented on src/metrics/metrics.py
> +    assert len(pc_points.shape) == 2, "Incorrect point cloud array size"
Давайте добавим "expected (n, 3)" во все такие ассерты

2022-02-08 16:59 UTC, DmiitriyJarosh commented on src/metrics/metrics.py
> +    assert len(pc_points.shape) == 2, "Incorrect point cloud array size"
и этот ассерт можно объединить с первым про len(shape)

2022-02-09 12:01 UTC, merged