Association metrics
pmokeev/plane-benchmark pull request #14
Opened 2022-08-15 07:42 UTC by vnmsklnk

This PR contains association metrics and tests for them

2022-08-15 07:58 UTC, achains commented on tests/test_assoc__points.py
> +    assert 1 == pytest.approx(quantitative_points(results, prev_planes))
Стоит придерживаться порядка наоборот: expected == actual

2022-08-16 05:30 UTC, DmiitriyJarosh requested changes

2022-08-16 05:30 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/assoc_metrics.py
> +    :param planes_from_previous_frame: set of planes from previous frame
как представить плоскость одним интом?

2022-08-16 05:30 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/assoc_metrics.py
> +        if (cur == prev) or (prev is None and cur not in planes_from_previous_frame):
а почему вообще они должны быть равны? ведь то что у нас ассоциация не значит что на разных кадрах у одни плоскостей один id. Фронтенд тому пример

2022-08-17 09:17 UTC, DmiitriyJarosh approved these changes

2022-08-21 20:37 UTC, DmiitriyJarosh requested changes

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/assoc_metrics.py
> +    labels_cur: NDArray[np.uint8],
а если у меня нет картинок? а есть только gt? например я работаю только с облаками

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/assoc_metrics.py
> +    labels_cur: NDArray[np.uint8],
еще не ясно почему в названии labeled_image_cur нет слова gt + непонятно что такое labels_cur - это картинка?

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +        labeled_image.reshape((labeled_image.shape[0] * labeled_image.shape[1], 3))
а в типе нельзя показать шэйп что это картинка в основном интерфейсе?

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +    del plane_color_dict[0]
почему? кто сказал что неразмеченные всегда первые? в либе есть константа для них

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +        if annot_num == 0:
аналогично что то странное

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +        if (colors[counts.argmax()] == 0).all():
опять ноль

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +        color = str(colors[counts.argmax()])
два раза просим аргмах, сохранить бы в переменную

2022-08-21 20:37 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +        plane_color_dict[annot_num] = colors[counts.argmax()]
сложно написано, можем проще или с комментами?

2022-08-28 06:30 UTC, DmiitriyJarosh approved these changes

2022-08-28 06:30 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/assoc_metrics.py
> +    for cur, _ in assoc_dict.items():
assoc_dict.keys()?

2022-08-28 06:30 UTC, DmiitriyJarosh commented on src/evops/assoc_metrics/matching.py
> +    for annot_num in annot_unique:
num? maybe better to use `label` suffix or just `annot`

2022-10-16 11:35 UTC, closed without merging