Dice and multivalue benchmarks implementation
pmokeev/plane-benchmark pull request #2
Opened 2022-02-09 14:27 UTC by pmokeev

2022-02-09 18:51 UTC, DmiitriyJarosh requested changes

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/DiceBenchmark.py
> +    gt_size = gt_indices.size
а может не стоит такие переменные делать мелкие?

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/DiceBenchmark.py
> +    gt_size = gt_indices.size
не намного стало читабельнее и короче

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +    truePositive = np.intersect1d(pred_indices, gt_indices).size
а куда ассерты пропали?

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +def accuracy(
а откуда это? не помню такой метрики у меня

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +def fScore(
и такой не помню. Зато пропущены missed, noise, under_segm_rate, over_segm_rate

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +    return truePositive / (falsePositive + truePositive)
это сложно - можно делить просто на pred_indices.size

2022-02-09 18:51 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +    return truePositive / (truePositive + falseNegative)
это сложно - можно делить просто на gt_indices.size

2022-02-10 11:59 UTC, DmiitriyJarosh requested changes

2022-02-10 11:59 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +        truePositive + trueNegative + falsePositive + falseNegative
это просто pc_points.size

2022-02-10 11:59 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +def fScore(
precision, accuracy, recall, fscore - в отдельный файл, они не связаны с тем что называется multi value benchmark

2022-02-10 11:59 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +def get_all_multi_value_metrics(
эта функция лишняя, вроде решили же

2022-02-10 11:59 UTC, DmiitriyJarosh commented on src/metrics/MultiValueBenchmark.py
> +def get_all_multi_value_metrics(
идея в ней неплохая, но пока мне не нравится как она смотрится, поэтому пока убираем вообще

2022-02-10 11:59 UTC, DmiitriyJarosh commented on src/utils/metrics.py
> +    Calculate if planes are overlapped enough (80%) to be used for PP-PR metric
хех, 80% в доках откуда? вы же даже дефолт value не выставили такое здесь. Думаю просто напишите что required_overlap показывает этот процент

2022-02-10 12:12 UTC, pmokeev commented on src/utils/metrics.py
> +    Calculate if planes are overlapped enough (80%) to be used for PP-PR metric
![изображение](https://user-images.githubusercontent.com/75482510/153406350-52cbe3b3-c1dd-4731-9a15-b39c5161916c.png)

2022-02-10 13:27 UTC, DmiitriyJarosh approved these changes

2022-02-10 13:27 UTC, DmiitriyJarosh commented on src/utils/metrics.py
> +    Calculate if planes are overlapped enough (80%) to be used for PP-PR metric
это доки не к этой функции ведь, на мой взгляд здесь дефолтное значение выглядит лишним - пусть оно останется только как было у метрики самой.

2022-02-10 14:39 UTC, merged